import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — ColdCraft',
  description: 'ColdCraft terms of service. Free tier limits, Pro subscription terms, and acceptable use.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-300">
      <div className="max-w-2xl mx-auto px-4 py-16">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors mb-10"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back
        </Link>

        <h1 className="text-3xl font-semibold text-white mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: April 2026</p>

        <div className="space-y-8 text-sm leading-relaxed">
          <section>
            <h2 className="text-white font-semibold text-base mb-3">1. Service description</h2>
            <p className="text-slate-400">
              ColdCraft is an AI-powered cold email generator available at{' '}
              <a href="https://coldcraft.rgwnd.app" className="text-blue-400 hover:text-blue-300">
                https://coldcraft.rgwnd.app
              </a>
              . The service generates cold email copy based on inputs you provide. By using ColdCraft, you agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">2. Free tier</h2>
            <p className="text-slate-400">
              The free tier allows up to <strong className="text-slate-300">3 email generations per day</strong>, tracked via a browser cookie. No account or sign-up is required for free use. ColdCraft reserves the right to adjust free tier limits at any time.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">3. Pro subscription</h2>
            <ul className="list-disc list-inside space-y-2 text-slate-400">
              <li>Pro subscriptions are billed monthly or annually via Stripe.</li>
              <li>You can cancel at any time through Stripe&apos;s customer portal or by contacting us.</li>
              <li>Cancellation takes effect at the end of the current billing period — no partial refunds are issued unless required by applicable law.</li>
              <li>Prices are listed in EUR and may be subject to applicable taxes depending on your location.</li>
              <li>ColdCraft reserves the right to change pricing with at least 30 days notice to active subscribers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">4. No guarantee of performance</h2>
            <p className="text-slate-400">
              ColdCraft generates email copy using AI. We do not guarantee that emails produced by ColdCraft will achieve any particular open rate, reply rate, or conversion outcome. Email performance depends on many factors outside our control, including your offer, prospect fit, and sending reputation.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">5. Acceptable use</h2>
            <p className="mb-3 text-slate-400">By using ColdCraft, you agree not to:</p>
            <ul className="list-disc list-inside space-y-2 text-slate-400">
              <li>Use the service to generate spam or unsolicited bulk email in violation of applicable laws (including CAN-SPAM, CASL, or GDPR)</li>
              <li>Attempt to circumvent rate limits through automated means, VPNs, or other techniques</li>
              <li>Use the service for harassment, phishing, or any other malicious purpose</li>
              <li>Resell or sublicense access to the service without written permission</li>
              <li>Interfere with or disrupt the service or its infrastructure</li>
            </ul>
            <p className="mt-3 text-slate-400">
              You are solely responsible for ensuring your outreach complies with the laws applicable in your jurisdiction and in the jurisdictions of your recipients.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">6. Intellectual property</h2>
            <p className="text-slate-400">
              The email copy generated by ColdCraft using your inputs is yours to use. ColdCraft retains ownership of the platform, software, and underlying technology.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">7. Limitation of liability</h2>
            <p className="text-slate-400">
              ColdCraft is provided &quot;as is&quot; without warranties of any kind. To the fullest extent permitted by law, ColdCraft shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">8. Changes to these terms</h2>
            <p className="text-slate-400">
              We may update these terms from time to time. The &quot;last updated&quot; date at the top will reflect changes. Continued use of the service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">9. Contact</h2>
            <p className="text-slate-400">
              Questions about these terms?{' '}
              <a href="mailto:support@coldcraft.app" className="text-blue-400 hover:text-blue-300">
                support@coldcraft.app
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
